---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trivy-scan   
spec:
  description: >-
    Trivy is a simple and comprehensive vulnerability scanner for containers and other artifacts. 

    It detects vulnerabilities of OS packages (Alpine, RHEL, CentOS, etc.) and application dependencies (Bundler, Composer, npm, yarn, etc.).

    Trivy can scan three different artifacts:
    1.  Container Images
    2.  Filesystem
    3.  Git Repositories

  params:
    - name: NO_PROXY
      description: Comma delimited list of hostnames or IP address which should be accessed directly without using the proxy service. eg. localhost,127.0.0.1,registry,example.com
      default: localhost,127.0.0.1
    - name: HTTP_PROXY
      description: Address of the proxy service to use for HTTP traffic in the following form {PROTOCOL}://{IP or HOSTNAME}:{PORT} eg. http://proxy.corp.example.com:8128 or https://user:password@proxy.corp.example.com:8128
      default: ''
    - name: REGISTRY_USERNAME
      description: The username of the private registry
      default: ''
    - name: REGISTRY_PASSWORD
      description: The password of the private registry
      default: ''
    - name: INSECURE_REGISTRY
      description: if image registry is insecure
      default: 'false'
    - name: SEVERITY_LEVELS
      description: Vulnerability severity level options are negligible, UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      default: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    - name: SCAN_TYPE
      description: Type of scan to perform (options are filesystem (fs), image (i), repository (repo))
      default: "image"  
    - name: SCAN_PATH_OR_IMAGE_URL
      description: scan path or image url
    - name: IGNORE_UNFIXED
      default:  'false'
      description:  To ignore unpatched/unfixed vulnerabilities 
    - name: VULN_TYPE
      default:  ''
      description:  Vulnerability type (options - os,library) Default if not specified - "os,library"
  workspaces:
  - name: local-image-repo
  steps:
    - name: trivy-scan-image
      image: registry.access.redhat.com/ubi8/ubi
      env:
      - name: NO_PROXY
        value:  $(params.NO_PROXY)
      - name: HTTP_PROXY
        value:  $(params.HTTP_PROXY)
      - name: HTTPS_PROXY
        value:  $(params.HTTP_PROXY)
      - name: TRIVY_NON_SSL
        value:  $(params.INSECURE_REGISTRY)
      - name: TRIVY_USERNAME
        value:  $(params.REGISTRY_USERNAME)  
      - name: TRIVY_PASSWORD
        value:  $(params.REGISTRY_PASSWORD)   

      workingDir: "/workspace/local-image-repo"
      script: |
        #!/bin/bash
        set +x

        curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin 

        echo "Trivy ..."
        IGNORE_UNFIXED=''
        if [ $(params.IGNORE_UNFIXED) == "true" ]; then  
            IGNORE_UNFIXED='--ignore-unfixed'
        fi
        VULN_TYPE=''
        if [ $(params.VULN_TYPE) != "" ]; then  
            VULN_TYPE='--vuln-type '$(params.VULN_TYPE)
        fi
        ls -la /workspace/local-image-repo 
        echo "Image to scan: "  $(params.SCAN_PATH_OR_IMAGE_URL)

        trivy $(params.SCAN_TYPE) --exit-code 1 --severity $(params.SEVERITY_LEVELS) \
        $IGNORE_UNFIXED $VULN_TYPE $(params.SCAN_PATH_OR_IMAGE_URL)

        retVal=$?
        echo "Return code is="$retVal
        if [ $retVal -ne 0 ]; then 
          echo "Scanning failed... vulnerability detected!"
        else
            echo "Scanning passed ... no vulnerability detected!" 
        fi
        exit $retVal
        
        
        
